INSERT INTO RODZAJPLATNOSCI(RODZAJPLATNOSCI_ID, RODZAJPLATNOSCI) VALUES (SEQ_RODZAJEPLATNOSCI.nextval, 'Credit Card');
INSERT INTO RODZAJPLATNOSCI(RODZAJPLATNOSCI_ID, RODZAJPLATNOSCI) VALUES (SEQ_RODZAJEPLATNOSCI.nextval, 'Debit Card');
INSERT INTO RODZAJPLATNOSCI(RODZAJPLATNOSCI_ID, RODZAJPLATNOSCI) VALUES (SEQ_RODZAJEPLATNOSCI.nextval, 'PayPal');
INSERT INTO RODZAJPLATNOSCI(RODZAJPLATNOSCI_ID, RODZAJPLATNOSCI) VALUES (SEQ_RODZAJEPLATNOSCI.nextval, 'Apple Pay');
INSERT INTO RODZAJPLATNOSCI(RODZAJPLATNOSCI_ID, RODZAJPLATNOSCI) VALUES (SEQ_RODZAJEPLATNOSCI.nextval, 'Google Pay');
INSERT INTO RODZAJPLATNOSCI(RODZAJPLATNOSCI_ID, RODZAJPLATNOSCI) VALUES (SEQ_RODZAJEPLATNOSCI.nextval, 'Amazon Pay');
INSERT INTO RODZAJPLATNOSCI(RODZAJPLATNOSCI_ID, RODZAJPLATNOSCI) VALUES (SEQ_RODZAJEPLATNOSCI.nextval, 'Direct Bank Transfer');
INSERT INTO RODZAJPLATNOSCI(RODZAJPLATNOSCI_ID, RODZAJPLATNOSCI) VALUES (SEQ_RODZAJEPLATNOSCI.nextval, 'Bitcoin');

















