INSERT INTO KATEGORIA(KATEGORIA_ID, NAZWA, OPIS) VALUES (SEQ_KATEGORIE.nextval, 'Laptopy', 'Kategoria Laptopy');
INSERT INTO KATEGORIA(KATEGORIA_ID, NAZWA, OPIS) VALUES (SEQ_KATEGORIE.nextval, 'Ultrabooki', 'Kategoria Ultrabooki');
INSERT INTO KATEGORIA(KATEGORIA_ID, NAZWA, OPIS) VALUES (SEQ_KATEGORIE.nextval, 'Komputery PC', 'Kategoria Komputery Stacjonarne');
INSERT INTO KATEGORIA(KATEGORIA_ID, NAZWA, OPIS) VALUES (SEQ_KATEGORIE.nextval, 'Tablety', 'Kategoria Tablety');
INSERT INTO KATEGORIA(KATEGORIA_ID, NAZWA, OPIS) VALUES (SEQ_KATEGORIE.nextval, 'Monitory', 'Kategoria Monitory');
INSERT INTO KATEGORIA(KATEGORIA_ID, NAZWA, OPIS) VALUES (SEQ_KATEGORIE.nextval, 'E-booki', 'Kategoria e-booki');
INSERT INTO KATEGORIA(KATEGORIA_ID, NAZWA, OPIS) VALUES (SEQ_KATEGORIE.nextval, 'Sluchawki', 'Kategoria sluchawki');
INSERT INTO KATEGORIA(KATEGORIA_ID, NAZWA, OPIS) VALUES (SEQ_KATEGORIE.nextval, 'Drukarki', 'Kategoria drukarki');
INSERT INTO KATEGORIA(KATEGORIA_ID, NAZWA, OPIS) VALUES (SEQ_KATEGORIE.nextval, 'Klawiatury komputerowe', 'Kategoria klawiatyry komputerowe');
INSERT INTO KATEGORIA(KATEGORIA_ID, NAZWA, OPIS) VALUES (SEQ_KATEGORIE.nextval, 'Myszki komputerowe', 'Kategoria myszki komputerowe');
INSERT INTO KATEGORIA(KATEGORIA_ID, NAZWA, OPIS) VALUES (SEQ_KATEGORIE.nextval, 'Oprogramowanie', 'Kategoria oprogramowanie');
INSERT INTO KATEGORIA(KATEGORIA_ID, NAZWA, OPIS) VALUES (SEQ_KATEGORIE.nextval, 'Podzespoly komputerowe', 'Kategoria podzespoly komputerowe');
INSERT INTO KATEGORIA(KATEGORIA_ID, NAZWA, OPIS) VALUES (SEQ_KATEGORIE.nextval, 'Routery', 'Kategoria routery');
INSERT INTO KATEGORIA(KATEGORIA_ID, NAZWA, OPIS) VALUES (SEQ_KATEGORIE.nextval, 'Glosniki komputerowe', 'Kategoria glosniki komputerowe');
INSERT INTO KATEGORIA(KATEGORIA_ID, NAZWA, OPIS) VALUES (SEQ_KATEGORIE.nextval, 'Kamery komputerowe', 'Kategoria kamery komputerowe');
INSERT INTO KATEGORIA(KATEGORIA_ID, NAZWA, OPIS) VALUES (SEQ_KATEGORIE.nextval, 'Kable i przejsciowki', 'Kategoria kable i przejsciowki');
INSERT INTO KATEGORIA(KATEGORIA_ID, NAZWA, OPIS) VALUES (SEQ_KATEGORIE.nextval, 'Urzadzenia sieciowe', 'Kategoria urzadzenia sieciowe');
INSERT INTO KATEGORIA(KATEGORIA_ID, NAZWA, OPIS) VALUES (SEQ_KATEGORIE.nextval, 'Akcesoria', 'Kategoria akcesoria');
