INSERT INTO ZAMOWIENIEPRODUKT(ZAMOWIENIEPRODUKT_ID, ZAMOWIENIE_ID, PRODUKT_ID, NUMERZAMOWIENIA, ILOSC, CENATOTAL, RABAT) VALUES (SEQ_ZAMOWIENIAPRODUKTY.nextval, 1, 1, 'A1B2C3', 2, 1200, 0);
INSERT INTO ZAMOWIENIEPRODUKT(ZAMOWIENIEPRODUKT_ID, ZAMOWIENIE_ID, PRODUKT_ID, NUMERZAMOWIENIA, ILOSC, CENATOTAL, RABAT) VALUES (SEQ_ZAMOWIENIAPRODUKTY.nextval, 2, 2, 'D4E5F6', 3, 900, 100);
INSERT INTO ZAMOWIENIEPRODUKT(ZAMOWIENIEPRODUKT_ID, ZAMOWIENIE_ID, PRODUKT_ID, NUMERZAMOWIENIA, ILOSC, CENATOTAL, RABAT) VALUES (SEQ_ZAMOWIENIAPRODUKTY.nextval, 3, 3, 'G7H8I9', 1, 700, 0);
INSERT INTO ZAMOWIENIEPRODUKT(ZAMOWIENIEPRODUKT_ID, ZAMOWIENIE_ID, PRODUKT_ID, NUMERZAMOWIENIA, ILOSC, CENATOTAL, RABAT) VALUES (SEQ_ZAMOWIENIAPRODUKTY.nextval,  4, 4, 'J0K1L2', 4, 1600, 200);
INSERT INTO ZAMOWIENIEPRODUKT(ZAMOWIENIEPRODUKT_ID, ZAMOWIENIE_ID, PRODUKT_ID, NUMERZAMOWIENIA, ILOSC, CENATOTAL, RABAT) VALUES (SEQ_ZAMOWIENIAPRODUKTY.nextval, 5, 5, 'M3N4O5', 2, 1000, 0);
INSERT INTO ZAMOWIENIEPRODUKT(ZAMOWIENIEPRODUKT_ID, ZAMOWIENIE_ID, PRODUKT_ID, NUMERZAMOWIENIA, ILOSC, CENATOTAL, RABAT) VALUES (SEQ_ZAMOWIENIAPRODUKTY.nextval, 6, 6, 'P6Q7R8', 1, 500, 0);
INSERT INTO ZAMOWIENIEPRODUKT(ZAMOWIENIEPRODUKT_ID, ZAMOWIENIE_ID, PRODUKT_ID, NUMERZAMOWIENIA, ILOSC, CENATOTAL, RABAT) VALUES (SEQ_ZAMOWIENIAPRODUKTY.nextval, 7, 7, 'S9T0U1', 2, 800, 0);
INSERT INTO ZAMOWIENIEPRODUKT(ZAMOWIENIEPRODUKT_ID, ZAMOWIENIE_ID, PRODUKT_ID, NUMERZAMOWIENIA, ILOSC, CENATOTAL, RABAT) VALUES (SEQ_ZAMOWIENIAPRODUKTY.nextval, 8, 8, 'V2W3X4', 3, 600, 0);
INSERT INTO ZAMOWIENIEPRODUKT(ZAMOWIENIEPRODUKT_ID, ZAMOWIENIE_ID, PRODUKT_ID, NUMERZAMOWIENIA, ILOSC, CENATOTAL, RABAT) VALUES (SEQ_ZAMOWIENIAPRODUKTY.nextval, 9, 9, 'Y5Z6A7', 1, 700, 0);
INSERT INTO ZAMOWIENIEPRODUKT(ZAMOWIENIEPRODUKT_ID, ZAMOWIENIE_ID, PRODUKT_ID, NUMERZAMOWIENIA, ILOSC, CENATOTAL, RABAT) VALUES (SEQ_ZAMOWIENIAPRODUKTY.nextval, 10, 10, 'B8C9D0', 4, 1200, 100);
INSERT INTO ZAMOWIENIEPRODUKT(ZAMOWIENIEPRODUKT_ID, ZAMOWIENIE_ID, PRODUKT_ID, NUMERZAMOWIENIA, ILOSC, CENATOTAL, RABAT) VALUES (SEQ_ZAMOWIENIAPRODUKTY.nextval, 11, 11, 'E1F2G3', 2, 800, 0);
INSERT INTO ZAMOWIENIEPRODUKT(ZAMOWIENIEPRODUKT_ID, ZAMOWIENIE_ID, PRODUKT_ID, NUMERZAMOWIENIA, ILOSC, CENATOTAL, RABAT) VALUES (SEQ_ZAMOWIENIAPRODUKTY.nextval, 12, 12, 'H4I5J6', 1, 600, 0);
INSERT INTO ZAMOWIENIEPRODUKT(ZAMOWIENIEPRODUKT_ID, ZAMOWIENIE_ID, PRODUKT_ID, NUMERZAMOWIENIA, ILOSC, CENATOTAL, RABAT) VALUES (SEQ_ZAMOWIENIAPRODUKTY.nextval, 13, 13, 'K7L8M9', 2, 1000, 50);
INSERT INTO ZAMOWIENIEPRODUKT (ZAMOWIENIEPRODUKT_ID, ZAMOWIENIE_ID, PRODUKT_ID, NUMERZAMOWIENIA, ILOSC, CENATOTAL, RABAT) VALUES (SEQ_ZAMOWIENIAPRODUKTY.nextval, 12, 1, 'D1E2F3', 2, 1000, 0);
INSERT INTO ZAMOWIENIEPRODUKT (ZAMOWIENIEPRODUKT_ID, ZAMOWIENIE_ID, PRODUKT_ID, NUMERZAMOWIENIA, ILOSC, CENATOTAL, RABAT) VALUES (SEQ_ZAMOWIENIAPRODUKTY.nextval, 13, 2, 'G4H5I6', 3, 800, 50);
INSERT INTO ZAMOWIENIEPRODUKT (ZAMOWIENIEPRODUKT_ID, ZAMOWIENIE_ID, PRODUKT_ID, NUMERZAMOWIENIA, ILOSC, CENATOTAL, RABAT) VALUES (SEQ_ZAMOWIENIAPRODUKTY.nextval, 14, 3, 'J7K8L9', 1, 600, 0);
INSERT INTO ZAMOWIENIEPRODUKT (ZAMOWIENIEPRODUKT_ID, ZAMOWIENIE_ID, PRODUKT_ID, NUMERZAMOWIENIA, ILOSC, CENATOTAL, RABAT) VALUES (SEQ_ZAMOWIENIAPRODUKTY.nextval, 15, 4, 'M0N1O2', 4, 1200, 150);
INSERT INTO ZAMOWIENIEPRODUKT (ZAMOWIENIEPRODUKT_ID, ZAMOWIENIE_ID, PRODUKT_ID, NUMERZAMOWIENIA, ILOSC, CENATOTAL, RABAT) VALUES (SEQ_ZAMOWIENIAPRODUKTY.nextval, 16, 5, 'P3Q4R5', 2, 900, 0);
INSERT INTO ZAMOWIENIEPRODUKT (ZAMOWIENIEPRODUKT_ID, ZAMOWIENIE_ID, PRODUKT_ID, NUMERZAMOWIENIA, ILOSC, CENATOTAL, RABAT) VALUES (SEQ_ZAMOWIENIAPRODUKTY.nextval, 17, 6, 'S6T7U8', 1, 500, 0);
INSERT INTO ZAMOWIENIEPRODUKT (ZAMOWIENIEPRODUKT_ID, ZAMOWIENIE_ID, PRODUKT_ID, NUMERZAMOWIENIA, ILOSC, CENATOTAL, RABAT) VALUES (SEQ_ZAMOWIENIAPRODUKTY.nextval, 18, 7, 'V9W0X1', 2, 800, 0);



