INSERT INTO SPEDYTOR(SPEDYTOR_ID, NAZWAFIRMY, NUMERTELEFONU) values (SEQ_SPEDYTORZY.nextval, 'FedEx', 67654467);
INSERT INTO SPEDYTOR(SPEDYTOR_ID, NAZWAFIRMY, NUMERTELEFONU) values (SEQ_SPEDYTORZY.nextval, 'UPS', 56783456);
INSERT INTO SPEDYTOR(SPEDYTOR_ID, NAZWAFIRMY, NUMERTELEFONU) values (SEQ_SPEDYTORZY.nextval, 'USPS', 45678979);
INSERT INTO SPEDYTOR(SPEDYTOR_ID, NAZWAFIRMY, NUMERTELEFONU) values (SEQ_SPEDYTORZY.nextval, 'DHL', 456787654);
INSERT INTO SPEDYTOR(SPEDYTOR_ID, NAZWAFIRMY, NUMERTELEFONU) values (SEQ_SPEDYTORZY.nextval, 'TNT', 56786543);
INSERT INTO SPEDYTOR(SPEDYTOR_ID, NAZWAFIRMY, NUMERTELEFONU) values (SEQ_SPEDYTORZY.nextval, 'DPD', 34567898);
INSERT INTO SPEDYTOR(SPEDYTOR_ID, NAZWAFIRMY, NUMERTELEFONU) values (SEQ_SPEDYTORZY.nextval, 'Aramex', 2345678);
INSERT INTO SPEDYTOR(SPEDYTOR_ID, NAZWAFIRMY, NUMERTELEFONU) values (SEQ_SPEDYTORZY.nextval, 'China Post', 34567890);
INSERT INTO SPEDYTOR(SPEDYTOR_ID, NAZWAFIRMY, NUMERTELEFONU) values (SEQ_SPEDYTORZY.nextval, 'Royal Mail', 987654);
INSERT INTO SPEDYTOR(SPEDYTOR_ID, NAZWAFIRMY, NUMERTELEFONU) values (SEQ_SPEDYTORZY.nextval, 'CourierIt', 98765677);


